@SwaggerApi_HostAddress = https://localhost:7082
@Id = 1

GET {{SwaggerApi_HostAddress}}/api/todos
Accept: application/json
CorrelationId: "71fbb6b3-fd14-4f8e-b7be-8a41b4840cf8"

###

GET {{SwaggerApi_HostAddress}}/api/todos/{{Id}}
Accept: application/json
CorrelationId: "71fbb6b3-fd14-4f8e-b7be-8a41b4840cf8"

###

POST {{SwaggerApi_HostAddress}}/api/todos
Accept: application/json
Content-Type: application/json
CorrelationId: "71fbb6b3-fd14-4f8e-b7be-8a41b4840cf8"

{
  "id": 11,
  "name": "Something else",
  "isComplete": false
}

###

DELETE {{SwaggerApi_HostAddress}}/api/todos/{{Id}}
Accept: application/json
CorrelationId: "71fbb6b3-fd14-4f8e-b7be-8a41b4840cf8"

###